export const KANNADA_NUMERALS: Record<string, string> = {
  '0': '೦',
  '1': '೧',
  '2': '೨',
  '3': '೩',
  '4': '೪',
  '5': '೫',
  '6': '೬',
  '7': '೭',
  '8': '೮',
  '9': '೯',
};

// ಸಂಖ್ಯೆಗಳನ್ನು ಇಂಗ್ಲಿಷ್ ಅಂಕಿಗಳಲ್ಲಿ ತೋರಿಸಲಾಗುತ್ತದೆ (ಓದುಗರ ಅನುಕೂಲಕ್ಕಾಗಿ)
export function toKannadaNumerals(value: number | string): string {
  return typeof value === 'number' ? value.toString() : value;
}

// ಅಗತ್ಯವಿದ್ದಲ್ಲಿ ಮಾತ್ರ ಕನ್ನಡ ಅಂಕಿ ಬಳಸಲು — ಉದಾ: ಆವರಣದಲ್ಲಿ (೧)
export function toKannadaDigits(value: number | string): string {
  const str = typeof value === 'number' ? value.toString() : value;
  return str.split('').map((char) => KANNADA_NUMERALS[char] || char).join('');
}

export const LOCAL_STRINGS = {
  appName: 'ಸಿದ್ಧಾಂತ ಶಿಖಾಮಣಿ',
  splashTagline: 'ಜ್ಞಾನದ ದೀಪವನ್ನು ಹುಳಿಕೊಳ್ಳಿ',
  home: 'ಮನೆ',
  chapters: 'ಅಧ್ಯಾಯಗಳು',
  search: 'ಹುಡುಕಿ',
  bookmarks: 'ಬುಕ್ಮಾರ್ಕುಗಳು',
  profile: 'ಪ್ರೊಫೈಲ್',
  settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
  loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
  welcome: 'ಸ್ವಾಗತ',
  welcomeMessage: 'ಆದ್ಯಾತ್ಮಿಕ ಜ್ಞಾನದ ಗುಹೆಗೆ ನಿಮ್ಮ ಪ್ರವಾಸಕ್ಕೆ ನೀವು ಸ್ವಾಗತ',
  continueReading: 'ಮುಂದುವರಿಸಿ ಓದಿ',
  recentChapters: 'ಇತ್ತೀಚಿನ ಅಧ್ಯಾಯಗಳು',
  allChapters: 'ಎಲ್ಲಾ ಅಧ್ಯಾಯಗಳು',
  recommended: 'ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ',
  viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
  readingProgress: 'ಓದುವ ಪ್ರಗತಿ',
  readingNow: 'ಈಗ ಓದುತ್ತಿದ್ದಾರೆ',
  startReading: 'ಓದಲು ಪ್ರಾರಂಭಿಸಿ',
  verses: 'ಶ್ಲೋಕಗಳು',
  minutes: 'ನಿಮಿಷಗಳು',
  searchPlaceholder: 'ಅಧ್ಯಾಯಗಳು ಅಥವಾ ಶ್ಲೋಕಗಳನ್ನು ಹುಡುಕಿ...',
  searchResults: 'ಹುಡುಕಾಟ ಫಲಿತಾಂಶಗಳು',
  noResults: 'ಯಾವುದೇ ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
  tryDifferent: 'ದಯವಿಟ್ಟು ವಿಭಿನ್ನ ಪದಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ',
  addBookmark: 'ಬುಕ್ಮಾರ್ಕ್ ಸೇರಿಸಿ',
  removeBookmark: 'ಬುಕ್ಮಾರ್ಕ್ ತೆಗೆದುಹಾಕಿ',
  addedBookmark: 'ಬುಕ್ಮಾರ್ಕ್ ಸೇರಿಸಲಾಗಿದೆ',
  removedBookmark: 'ಬುಕ್ಮಾರ್ಕ್ ತೆಗೆದುಹಾಕಲಾಗಿದೆ',
  noBookmarks: 'ಇನ್ನೂ ಯಾವುದೇ ಬುಕ್ಮಾರ್ಕ್‌ಗಳಿಲ್ಲ',
  addFirstBookmark: 'ಓದುವಾಗ ಮುಖ್ಯ ಪುಟಗಳಿಗೆ ಬುಕ್ಮಾರ್ಕ್ ಸೇರಿಸಿ',
  chapter: 'ಅಧ್ಯಾಯ',
  verse: 'ಶ್ಲೋಕ',
  of: 'ದಲ್ಲಿ',
  translation: 'ಭಾಷಾಂತರ',
  commentary: 'ವ್ಯಾಖ್ಯಾನ',
  previous: 'ಹಿಂದಿನ',
  next: 'ಮುಂದಿನ',
  back: 'ಹಿಂದಕ್ಕೆ',
  save: 'ಉಳಿಸಿ',
  cancel: 'ರದ್ದು',
  confirm: 'ದೃಢಪಡಿಸಿ',
  share: 'ಹಂಚಿಕೊಳ್ಳಿ',
  copy: 'ನಕಲಿಸಿ',
  copied: 'ನಕಲಿಸಲಾಗಿದೆ',
  settingsTitle: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
  display: 'ಪ್ರದರ್ಶನ',
  reading: 'ಓದುವಿಕೆ',
  general: 'ಸಾಮಾನ್ಯ',
  about: 'ಬಗ್ಗೆ',
  fontSize: 'ಫಾಂಟ್ ಗಾತ್ರ',
  fontFamily: 'ಫಾಂಟ್ ಕುಟುಂಬ',
  small: 'ಚಿಕ್ಕ',
  medium: 'ಮಧ್ಯಮ',
  large: 'ದೊಡ್ಡ',
  extraLarge: 'ವಿಶಾಲ',
  serif: 'ಸೆರಿಫ್',
  sans: 'ಸ್ಯಾನ್ಸ್',
  showSanskrit: 'ಸಂಸ್ಕೃತ ಪಠ್ಯ ತೋರಿಸಿ',
  showTranslation: 'ಭಾಷಾಂತರ ತೋರಿಸಿ',
  showCommentary: 'ವ್ಯಾಖ್ಯಾನ ತೋರಿಸಿ',
  vibration: 'ವೈಬ್ರೇಷನ್',
  vibrationDesc: 'ಬಟನ್ ಒತ್ತಿದಾಗ ಸೂಚನೆ ವೈಬ್ರೇಷನ್',
  autoSave: 'ಸ್ವಯಂಚಾಲಿತ ಪ್ರಗತಿ',
  autoSaveDesc: 'ಓದುವ ಪ್ರಗತಿಯನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಉಳಿಸಿ',
  profileTitle: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
  name: 'ಹೆಸರು',
  joined: 'ಸೇರಿದ ದಿನಾಂಕ',
  stats: 'ಅಂಕಿಅಂಶಗಳು',
  chaptersCompleted: 'ಪೂರ್ಣಗೊಂಡ ಅಧ್ಯಾಯಗಳು',
  versesRead: 'ಓದಿದ ಶ್ಲೋಕಗಳು',
  readingStreak: 'ಓದುವ ಸಾಲು',
  days: 'ದಿನಗಳು',
  totalTime: 'ಒಟ್ಟು ಸಮಯ',
  hours: 'ಗಂಟೆಗಳು',
  achievements: 'ಸಾಧನೆಗಳು',
  noAchievements: 'ಇನ್ನೂ ಸಾಧನೆಗಳಿಲ್ಲ',
  version: 'ವೆರ್ಷನ್',
  language: 'ಭಾಷೆ',
  kannada: 'ಕನ್ನಡ',
  appDescription: 'ಆದ್ಯಾತ್ಮಿಕತೆ ಮತ್ತು ದರ್ಶನಶಾಸ್ತ್ರದ ಪ್ರಕಾಶಮಾನ ಬೋಧನೆಗಳಿಗೆ ಮಾರ್ಗದರ್ಶಕ',
  startExploring: 'ಅನ್ವೇಷಿಸಲು ಪ್ರಾರಂಭಿಸಿ',
  continueExplore: 'ಅನ್ವೇಷಣೆಯನ್ನು ಮುಂದುವರಿಸಿ',
  completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
  inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿ',
  notStarted: 'ಪ್ರಾರಂಭವಾಗಿಲ್ಲ',
  category: 'ವರ್ಗ',
  sankhya: 'ಸಂಖ್ಯಾ',
  yoga: 'ಯೋಗ',
  jnana: 'ಜ್ಞಾನ',
  bhakti: 'ಭಕ್ತಿ',
  vairagya: 'ವೈರಾಗ್ಯ',
  note: 'ಟಿಪ್ಪಣಿ',
  addNote: 'ಟಿಪ್ಪಣಿ ಸೇರಿಸಿ',
  noNote: 'ಟಿಪ್ಪಣಿ ಇಲ್ಲ',
  filter: 'ಫಿಲ್ಟರ್',
  sort: 'ವರ್ಗೀಕರಿಸಿ',
  sortByNumber: 'ಸಂಖ್ಯೆಯ ಪ್ರಕಾರ',
  sortByProgress: 'ಪ್ರಗತಿಯ ಪ್ರಕಾರ',
  sortByRecent: 'ಇತ್ತೀಚಿನ',
  sortByTitle: 'ಶೀರ್ಷಿಕೆಯ ಪ್ರಕಾರ',
  reset: 'ಮರಳಿ ಸ್ಥಾಪಿಸಿ',
  feedback: 'ಪ್ರತಿಕ್ರಿಯೆ',
  rateApp: 'ಅಪ್ಲಿಕೇಶನ್ ರೇಟ್ ಮಾಡಿ',
  shareApp: 'ಅಪ್ಲಿಕೇಶನ್ ಹಂಚಿಕೊಳ್ಳಿ',
  privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
  termsOfService: 'ಸೇವೆಯ ನಿಯಮಗಳು',
  developerInfo: 'ಡೆವಲಪರ್ ಮಾಹಿತಿ',
  madeWithLove: 'ಪ್ರೀತಿಯಿಂದ ಮಾಡಲಾಗಿದೆ',
  emptyState: 'ಯಾವುದೇ ಮಾಹಿತಿ ಇಲ್ಲ',
  errorOccurred: 'ದೋಷ ಸಂಭವಿಸಿದೆ',
  retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
  somethingWentWrong: 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
  pleaseTryAgain: 'ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
  networkError: 'ನೆಟ್ವರ್ಕ್ ದೋಷ',
  checkConnection: 'ನಿಮ್ಮ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ',
  chapterNotFound: 'ಅಧ್ಯಾಯ ಕಂಡುಬಂದಿಲ್ಲ',
  verseNotFound: 'ಶ್ಲೋಕ ಕಂಡುಬಂದಿಲ್ಲ',
  appTagline: 'ಜ್ಞಾನವೇ ಮುಕ್ತಿ ಮಾರ್ಗ',
  dailyQuote: 'ಗುರು, ಲಿಂಗ, ಜಂಗಮಗಳ ಸೇವೆಯೇ ಶಿವನ ಆರಾಧನೆ.',
  dailyQuoteAuthor: 'ಶಿವಯೋಗಿ ಶಿವಾಚಾರ್ಯರು',
  quickAccess: 'ತ್ವರಿತ ಪ್ರವೇಶ',
  dailyShloka: 'ದೈನಂದಿನ ಶ್ಲೋಕ',
  readNow: 'ಓದಿ',
  pariccheda: 'ಪರಿಚ್ಛೇದ',
  chaptersPariccheda: 'ಅಧ್ಯಾಯಗಳು (ಪರಿಚ್ಛೇದಗಳು)',
  shlokas: 'ಶ್ಲೋಕಗಳು',
  notes: 'ನೋಟ್‌ಗಳು',
  more: 'ಹೆಚ್ಚು',
  audio: 'ಆಡಿಯೋ',
  shodhane: 'ಶೋಧನೆ',
  kannadaBhavartha: 'ಕನ್ನಡ ಭಾವಾರ್ಥ',
  previousShloka: 'ಹಿಂದಿನ ಶ್ಲೋಕ',
  nextShloka: 'ಮುಂದಿನ ಶ್ಲೋಕ',
  searchHint: 'ಶ್ಲೋಕ, ಪದ ಅಥವಾ ವಿಷಯವನ್ನು ಹುಡುಕಿ...',
  seeAllResults: 'ಎಲ್ಲಾ ಫಲಿತಾಂಶಗಳನ್ನು ನೋಡಿ',
  words: 'ಪದಗಳು',
  topics: 'ವಿಷಯಗಳು',
  all: 'ಎಲ್ಲಾ',
  writeNote: 'ನೋಟ್ ಬರೆಯಿರಿ',
};
